language: ruby
cache: bundler
sudo: false

before_install: ./travis/before_install
bundler_args: --without=development

rvm: 2.3.4
matrix:
  include:
    - env: VAGRANT_VERSION=v1.9.7
    - env:
        - VAGRANT_VERSION=v1.8.7
        - BUNDLER_VERSION=1.12.5
      rvm: 2.2.5
    - env: VAGRANT_VERSION=v1.7.4
      rvm: 2.0.0
    - env:
        - VAGRANT_VERSION=v1.6.5
        - BUNDLER_VERSION="< 1.7.0, >= 1.5.2"
      rvm: 2.0.0
      gemfile: travis/Gemfile_1.6.5
    - env:
        - VAGRANT_VERSION=v1.5.4
        - BUNDLER_VERSION="~> 1.5.2"
      rvm: 2.0.0
    - env: VAGRANT_VERSION=v1.4.3
      rvm: 2.0.0
    - env: VAGRANT_VERSION=master
  allow_failures:
    - env: VAGRANT_VERSION=master
